import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F7F2EA",
  },
  container: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 36,
    paddingBottom: 18,
  },
  header: {
    marginBottom: 20,
  },
  greeting: {
    fontSize: 32,
    fontWeight: "800",
    color: "#211A16",
  },
  subtitle: {
    fontSize: 15,
    color: "#7A6F66",
    marginTop: 5,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "#211A16",
  },
  balanceCard: {
    backgroundColor: "#2F241D",
    borderRadius: 28,
    padding: 24,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 5,
  },
  cardLabel: {
    fontSize: 15,
    color: "#E8DCCF",
  },
  totalAmount: {
    fontSize: 44,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 8,
  },
  cardSmallText: {
    fontSize: 13,
    color: "#D6C7B8",
    marginTop: 8,
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 26,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statLabel: {
    fontSize: 13,
    color: "#8A8178",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#2F241D",
    marginTop: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: "800",
    color: "#211A16",
  },
  seeAll: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8B5E3C",
  },
  listContent: {
    paddingBottom: 18,
  },
  transactionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 15,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  transactionLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F1E7DA",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  iconText: {
    fontSize: 20,
  },
  merchant: {
    fontSize: 16,
    fontWeight: "800",
    color: "#211A16",
  },
  transactionDetails: {
    fontSize: 13,
    color: "#8A8178",
    marginTop: 4,
  },
  amount: {
    fontSize: 16,
    fontWeight: "800",
    color: "#B45309",
  },
  button: {
    backgroundColor: "#2F241D",
    borderRadius: 22,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 4,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
  categoryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  categoryName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#211A16",
  },
  categoryArrow: {
    fontSize: 28,
    color: "#8A8178",
  },
    authContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 70,
  },
  authTitle: {
    fontSize: 36,
    fontWeight: "900",
    color: "#211A16",
  },
  authCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 26,
    padding: 20,
    marginTop: 28,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#211A16",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#F7F2EA",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#211A16",
  },
  secondaryButton: {
    borderWidth: 1.5,
    borderColor: "#2F241D",
    borderRadius: 22,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 12,
  },
  secondaryButtonText: {
    color: "#2F241D",
    fontSize: 16,
    fontWeight: "800",
  },
    logoutButton: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#B45309",
    borderRadius: 22,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 18,
  },
  logoutButtonText: {
    color: "#B45309",
    fontSize: 16,
    fontWeight: "800",
  },
    centeredContainer: {
    flex: 1,
    backgroundColor: "#F7F2EA",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#7A6F66",
    fontSize: 15,
    marginTop: 12,
  },
  emptyText: {
    color: "#7A6F66",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
    titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addSmallButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#2F241D",
    justifyContent: "center",
    alignItems: "center",
  },
  addSmallButtonText: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 2,
  },
  swipeDeleteAction: {
    backgroundColor: "#B45309",
    justifyContent: "center",
    alignItems: "center",
    width: 88,
    marginBottom: 12,
    borderTopRightRadius: 22,
    borderBottomRightRadius: 22,
  },
  swipeDeleteText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  categoryTotal: {
    fontSize: 16,
    fontWeight: "800",
    color: "#B45309",
  },
});